apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: naro-vorn3227-spring-next-certificate
  namespace: naro-vorn3227-spring-next
spec:
  secretName: naro-vorn3227-spring-next-secret-tls
  commonName: naro-vorn3227-spring-next.assessify.org
  dnsNames:
  - naro-vorn3227-spring-next.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
